name: Build

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag for release (e.g., v1.0.6.3.r)'
        required: true
        default: 'v1.0.6.3'
  push:
    tags:
      - 'v*'  # Trigger only on version tags like v1.0, v1.2.3 etc.

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    env:
      SOLUTION_PATH: 'FrostyEditor/FrostyEditor.sln'
      BUILD_CONFIGURATION: 'Release - Final'
      BUILD_PLATFORM: 'x64'
      MODMANAGER_OUTPUT_PATH: 'FrostyModManager/bin/Release/Final'
      EDITOR_OUTPUT_PATH: 'FrostyEditor/bin/Release/Final'
      MODMANAGER_ZIP: 'FrostyModManager.zip'
      EDITOR_ZIP: 'FrostyEditor.zip'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore $env:SOLUTION_PATH

    - name: Build with MSBuild
      run: msbuild $env:SOLUTION_PATH /p:Configuration="$env:BUILD_CONFIGURATION" /p:Platform="$env:BUILD_PLATFORM"

    - name: Zip FrostyModManager
      run: |
        Compress-Archive -Path "$env:MODMANAGER_OUTPUT_PATH\*" -DestinationPath $env:MODMANAGER_ZIP

    - name: Zip FrostyEditor
      run: |
        Compress-Archive -Path "$env:EDITOR_OUTPUT_PATH\*" -DestinationPath $env:EDITOR_ZIP

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.event.inputs.tag_name || github.ref_name }}
        tag_name: ${{ github.event.inputs.tag_name || github.ref_name }}
        files: |
          ${{ env.MODMANAGER_ZIP }}
          ${{ env.EDITOR_ZIP }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
